- hosts: all
  gather_facts: false
  vars:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
  - name: "Add ssh key"
    authorized_key:
      user: ubuntu
      key: "{{ ssh_pub_key }}"
  - name: "Install packages"
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - docker
      - docker.io
      - curl
      - apt-transport-https
      - bridge-utils
  - name: "Add br_netfilter kernel module"
    modprobe:
      name: "br_netfilter"
  - name: "Letting iptables see bridged traffic"
    sysctl:
      name: "net.bridge.bridge-nf-call-iptables"
      value: "1"
      sysctl_file: "/etc/sysctl.d/k8s.conf"
      reload: yes
  - name: "Add k8s repo key"
    apt_key:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - name: "Adding k8s repo"
    apt_repository:
      repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      filename: "kubernetes"
  - name: "Installing kubeadm, kubelet and kubectl"
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
  - name: "Enable docker"
    systemd:
      name: docker
      state: started
      enabled: yes


